module Api::V1::MsgsConst
	HEADERS_MSG = "Please provide Authorization in headers"
	INVALID_AUTH = "Invalid Authentication"
	GOOD_TOKEN_MSG = "token is good"
	NO_MORE_TOKEN_MSG  = "No more token!"
	MISSING_PARAMS_MSG = "Missing parameters"
	INVALID_CREDENTIALS = "Invalid Authentication"
	INVALID_AUTH= 'Invalid Authentication'
	BOOKING= 'Booking saved'
	BOOKING_FAILED="Booking cannot be saved"
	CHARITIE_NOT_FOUND="Charitie not found."
	NOT_AN_ADMIN="You are not an admin."
	REQUIRED_ATTRIBUTES="Please send all required attributes"
	CHARITIE_ERROR="An error occurred on creating charitie"
	INVALID_EMAIL="Please enter a valid email address."
	INVALID_CHARITIE="An error occurred on creating charitie"
	INVALID_UPDATE_CHARITIE="An error occurred on updating charitie"
	CLIENT_NOT_FOUND_MSG = "Client not found or not a business."
	INVALID_CREDENTIALS_MSG = "Invalid Authentication"
	CONTACT_CANNOT_DELETED_MSG  = "Contact Can not be deleted"
	CONTACTS_PARAMS_MSG = "Please send all require attributes."
	NOT_ADMIN_MSG = "You are not an admin."
	TYPE_ERROR_MSG  = "Please send type attributes."
	HEARDOFUS_NOT_FOUND_MSG = "HeardOfUs not found."
	TYPE_ALREADY_ERROR_MSG = "Type already exist."
end